language: python

# currently required for Python 3.7
sudo: required
dist: xenial

python:
    - "3.7"

# install other libraries using pip
install:
    - pip install -U setuptools
    - pip install -Ue .[dev,zmq,msgpack]

# command to run tests
script: pytest
