language: python

# using container based testing is faster, but you can't use sudo
sudo: false

python:
    - "3.7"
#    - "2.7"

# install other libraries using pip
install:
    - pip install -U setuptools
    - pip install -Ue .[test]

# command to run tests
script: pytest
